### ISSUE TITLE
gebruik makefiles

### ISSUE THREAD

**Issue by raoulg** [megamaster4/dme_hu_maxpot#1]
Je code ziet er uitstekend uit, maar suggestie:

een makefile met een recept om alles te doen (make all)
en ook de linting via make lint

Eventueel een lefthook.yml file https://github.com/evilmartians/lefthook dan hoef je dat niet meer zelf te doen.

**Comment by megamaster4** [comment]
Makefile toegevoegd in 6aa63a53f634795a141b2ed95f983a4b99474f64
