### ISSUE TITLE
psycopg2 fails to install

### ISSUE THREAD

**Issue by raoulg** [megamaster4/dme_hu_maxpot#3]
```
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rgrouls/Library/Application Support/pdm/venv/lib/python3.11/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.

If you prefer to avoid building psycopg2 from source, please install the PyPI
'psycopg2-binary' package instead.

For further information please check the 'doc/src/install.rst' file (also at
<https://www.psycopg.org/docs/install.html>).


See /var/folders/kh/3x29jv311r70s04_14wxhxmm0000gn/T/pdm-install-yb91sd8b.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback
```

Ik heb psycopg2-binary toegevoegd, dat installeert in ieder geval zonder fouten. Ik zal wel een pull request maken, ik weet niet zeker of dit een goede fix is.

**Comment by megamaster4** [comment]
Ah dat issue heb ik wel eens gezien bij Azure Function Apps, waarbij een linux backend gebruikt wordt.

**Comment by megamaster4** [comment]
`psycopg2-binary` is prima voor development lees ik, indien het voor productie gebruikt wordt, lees ik dat je op een linux omgeving "libpq-dev" moet installeren die een aantal dependencies voor postgresql installeerd. Voor nu hou ik hem even op `psycopg2-binary`
https://stackoverflow.com/questions/58487992/how-to-install-libpq-dev-for-psycopg2-in-docker
